-- 코드를 입력하세요
WITH UNI AS (
    SELECT ONLINE_SALE_ID, USER_ID, NULL AS OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM ONLINE_SALE 
    UNION ALL
    SELECT NULL, NULL, OFFLINE_SALE_ID, PRODUCT_ID, SALES_AMOUNT, SALES_DATE FROM OFFLINE_SALE 
)


SELECT 
    DATE_FORMAT(SALES_DATE,'%Y-%m-%d') AS SALES_DATE, 
    PRODUCT_ID, 
    CASE
        WHEN OFFLINE_SALE_ID IS NOT NULL THEN NULL
        ELSE USER_ID
    END AS USER_ID, 
    SALES_AMOUNT
FROM UNI
WHERE YEAR(UNI.SALES_DATE) = 2022 AND MONTH(UNI.SALES_DATE) = 03
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID