-- 코드를 작성해주세요
WITH SECOND AS(
    SELECT C.ID AS ID FROM ECOLI_DATA C INNER JOIN ECOLI_DATA P ON P.ID = C.PARENT_ID AND P.PARENT_ID IS NULL
)

SELECT ID FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT * FROM SECOND)
ORDER BY ID